// bridge/src/angular/angular-bridge.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  Injectable,
  inject,
  signal,
  OnDestroy,
  Type,
  Provider,
  EnvironmentProviders,
  makeEnvironmentProviders,
} from '@angular/core';
import {
  A2uiRendererService,
  A2UI_RENDERER_CONFIG,
  provideMarkdownRenderer,
} from '@a2ui/angular/v0_9';
import {Catalog, ComponentApi, FunctionImplementation} from '@a2ui/web_core/v0_9';
import {
  a2uiBridge,
  ThemePreference,
  RendererProcessor,
  SurfaceStateSubscription,
  CatalogDetails,
  createMcpCatalogFunctions,
  type ComponentUsages,
} from '../index.js';

export const BASIC_WITH_MCP_CATALOG_ID =
  'https://a2ui.org/specification/v0_9/catalogs/basic_with_mcp/catalog.json';

function extractCatalogEntries<T>(collection?: ReadonlyMap<string, T> | Record<string, T>): T[] {
  if (!collection) return [];
  if (typeof (collection as ReadonlyMap<string, T>).values === 'function') {
    return Array.from((collection as ReadonlyMap<string, T>).values());
  }
  return Object.values(collection);
}

export interface AngularSandboxOptions {
  /** Optional custom markdown rendering delegate callback hook */
  markdownRendererFn?: (markdown: string) => Promise<string>;
  /** Optional preloaded catalog JSON data, provided directly in memory. */
  catalogJson?: unknown;
  /** Optional callback to retrieve component usage samples. */
  getComponentUsages?: () => Promise<ComponentUsages>;
  /** Optional callback when theme changes. */
  onThemeChange?: (theme: ThemePreference) => void;
}

/**
 * Orchestrates mapping surface mount/unmount lifecycles, connection handshakes,
 * and reactive state tracking between the host dashboard shell and the local
 * sandbox view elements.
 */
@Injectable()
export class A2uiSandboxConnection implements OnDestroy {
  /**
   * The active surface canvas identifier mounted by the host container. Bind
   * this value to the HTML template.
   */
  readonly surfaceId = signal('');

  /** Resolves the central rendering service provider from the injector context. */
  private readonly rendererService: A2uiRendererService = inject(A2uiRendererService);

  /** Injected dynamic renderer configuration options block. */
  private readonly rendererConfig: {catalogs: unknown[]} = inject(A2UI_RENDERER_CONFIG);

  /** The dynamic teardown handle for the active framework renderer connection subscription. */
  private rendererConnection: SurfaceStateSubscription | null = null;

  /**
   * Initializes a new instance of the sandbox connection, automatically establishing
   * the message transport pipeline.
   *
   * Subscribes to the global preview bridge singleton, mapping dynamic renderer callbacks
   * (onSurfaceReady and onSurfaceCleared) directly to local reactive state signals.
   */
  constructor(
    catalogJson?: unknown,
    getComponentUsages?: () => Promise<ComponentUsages>,
    onThemeChange?: (theme: ThemePreference) => void,
  ) {
    const processor: RendererProcessor = {
      processMessages: payload =>
        (this.rendererService as unknown as RendererProcessor).processMessages(payload),
    };
    this.rendererConnection = a2uiBridge.attachRenderer(processor, {
      surfaceGroup: this.rendererService.surfaceGroup,
      onCatalogResolved: (catalogId: string) => {
        const catalogs = this.rendererConfig.catalogs;
        if (catalogs) {
          for (const catalog of catalogs) {
            if (catalog) {
              (catalog as unknown as CatalogDetails).id = catalogId;
            }
          }
        }
      },
      onSurfaceReady: (surfaceId: string) => {
        this.surfaceId.set(surfaceId);
      },
      onSurfaceCleared: () => {
        this.surfaceId.set('');
      },
      catalogJson: catalogJson,
      getComponentUsages: getComponentUsages,
      onThemeChange: onThemeChange,
    });
  }

  /**
   * Performs cleanups during sandbox destruction.
   * Disposes active bridge connections and releases event listener subscriptions
   * to prevent memory leaks and observer bloat in high-frequency test runs.
   */
  ngOnDestroy(): void {
    this.rendererConnection?.unsubscribe();
    this.rendererConnection = null;
  }
}

/**
 * Provides a unified array of Angular dependency injection providers configured for the A2UI sandbox.
 *
 * Exposes a standardized registration block that includes catalog component classes, the central
 * rendering service, and the sandbox connection state to keep catalog bootstrap clean and modular.
 *
 * @param catalogsClasses The array of catalog component provider classes (e.g. BasicCatalog) to register and manage.
 * @param options Optional configuration adapter block holding local catalogJson and markdownRendererFn hook delegates.
 * @return Angular EnvironmentProviders ready for modern standalone bootstrapping application scopes.
 */
export function provideA2uiSandbox(
  catalogsClasses: Array<Type<Catalog<ComponentApi>>>,
  options?: AngularSandboxOptions,
): EnvironmentProviders {
  const providers: Provider[] = [
    A2uiRendererService,
    {
      provide: A2uiSandboxConnection,
      useFactory: () =>
        new A2uiSandboxConnection(
          options?.catalogJson,
          options?.getComponentUsages,
          options?.onThemeChange,
        ),
    },
    ...catalogsClasses,
    provideMarkdownRenderer(options?.markdownRendererFn),
    {
      provide: A2UI_RENDERER_CONFIG,
      useFactory: () => {
        const resolvedCatalogs = catalogsClasses.map(cls => inject(cls));
        const baseCatalog = resolvedCatalogs[0];
        const baseComponents = extractCatalogEntries<ComponentApi>(baseCatalog?.components);
        const baseFunctions = extractCatalogEntries<FunctionImplementation>(baseCatalog?.functions);
        const mcpFunctions = createMcpCatalogFunctions(
          {
            processMessages: msgs => {
              const activeProcessor = (
                a2uiBridge as unknown as {activeRenderer?: {processor?: RendererProcessor}}
              ).activeRenderer?.processor;
              activeProcessor?.processMessages(msgs);
            },
          },
          async () => a2uiBridge.getMcpClient(),
        );
        const mcpCatalog = new Catalog(BASIC_WITH_MCP_CATALOG_ID, baseComponents, [
          ...baseFunctions,
          ...mcpFunctions,
        ]);
        return {
          catalogs: [mcpCatalog, ...resolvedCatalogs],
          actionHandler: (action: unknown) => {
            a2uiBridge.sendAction(action);
          },
        };
      },
    },
  ];
  return makeEnvironmentProviders(providers);
}

// bridge/src/react/react-bridge.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, useEffect} from 'react';
import {
  MessageProcessor,
  SurfaceModel,
  Catalog,
  ComponentApi,
  FunctionImplementation,
  A2uiClientAction,
} from '@a2ui/web_core/v0_9';
import {
  a2uiBridge,
  ThemePreference,
  CatalogDetails,
  ComponentUsages,
  createMcpCatalogFunctions,
} from '../index.js';

export const BASIC_WITH_MCP_CATALOG_ID =
  'https://a2ui.org/specification/v0_9/catalogs/basic_with_mcp/catalog.json';

function extractCatalogEntries<T>(collection?: ReadonlyMap<string, T> | Record<string, T>): T[] {
  if (!collection) return [];
  if (typeof (collection as ReadonlyMap<string, T>).values === 'function') {
    return Array.from((collection as ReadonlyMap<string, T>).values());
  }
  return Object.values(collection);
}

export interface UseA2uiSandboxResult<C extends ComponentApi = ComponentApi> {
  /** The reactive dynamic surface drawing model representing the active canvas. */
  surface: SurfaceModel<C> | undefined;
}

export interface ReactSandboxOptions {
  /** Optional preloaded catalog JSON data, provided directly in memory. */
  catalogJson?: unknown;
  /** Optional callback to retrieve component usage samples. */
  getComponentUsages?: () => Promise<ComponentUsages>;
  /** Optional callback when theme changes. */
  onThemeChange?: (theme: ThemePreference) => void;
}

/**
 * A dynamic React hook that orchestrates the inter-frame PreviewBridge connection.
 * Automatically registers state observers, binds catalog processors, maps surface lifecycle
 * events reactively, and dispatches dynamic unmount cleanups during hook unmount to prevent memory leaks.
 *
 * @param catalogs The array of component catalogs matching A2UI specifications.
 * @param options Optional configuration payloads.
 * @return A reactive state object containing the active surface drawing model.
 */
export function useA2uiSandbox<C extends ComponentApi = ComponentApi>(
  catalogs: Catalog<C>[],
  options?: ReactSandboxOptions,
): UseA2uiSandboxResult<C> {
  const [surface, setSurface] = useState<SurfaceModel<C> | undefined>(undefined);

  useEffect(() => {
    const procRef: {current?: MessageProcessor<C>} = {};
    const baseCatalog = catalogs[0];
    const baseComponents = extractCatalogEntries<C>(baseCatalog?.components);
    const baseFunctions = extractCatalogEntries<FunctionImplementation>(baseCatalog?.functions);
    const mcpFunctions = createMcpCatalogFunctions(
      {
        processMessages: msgs => procRef.current?.processMessages(msgs),
      },
      async server => a2uiBridge.getMcpClient(server),
    );
    const mcpCatalog = new Catalog<C>(BASIC_WITH_MCP_CATALOG_ID, baseComponents, [
      ...baseFunctions,
      ...mcpFunctions,
    ]);
    const runtimeCatalogs = [mcpCatalog, ...catalogs];

    // Instantiates a new dynamic MessageProcessor mapping outbound event actions
    const processor = new MessageProcessor(runtimeCatalogs, (action: A2uiClientAction) => {
      a2uiBridge.sendAction(action);
    });
    procRef.current = processor;

    // Connects the renderer stack and establishes inter-frame callbacks
    const connection = a2uiBridge.attachRenderer(processor, {
      surfaceGroup: processor.model,
      catalogJson: options?.catalogJson,
      getComponentUsages: options?.getComponentUsages,
      onThemeChange: options?.onThemeChange,
      onCatalogResolved: catalogId => {
        for (const catalog of runtimeCatalogs) {
          if (catalog) {
            (catalog as unknown as CatalogDetails).id = catalogId;
          }
        }
      },
      onSurfaceReady: surfaceId => {
        setSurface(processor.model.getSurface(surfaceId));
      },
      onSurfaceCleared: () => {
        setSurface(undefined);
      },
    });

    // Standard React Hook cleanup: disposes connections and releases event listener subscriptions
    return () => {
      connection.unsubscribe();
    };
  }, []);

  return {surface};
}
